version: '3'
services:
  app:
    image: engineer442/spring-boot-application:${BUILD_ID}
    ports:
      - "8080:8080"
  nginx:
    image: engineer442/spring-boot-application-nginx:${BUILD_ID}
    ports:
      - "80:80"
    depends_on:
      - app
